#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x38EE757D69184620 (lasse.collin@tukaani.org)
#
Name     : xz
Version  : 5.2.4
Release  : 46
URL      : http://tukaani.org/xz/xz-5.2.4.tar.gz
Source0  : http://tukaani.org/xz/xz-5.2.4.tar.gz
Source99 : http://tukaani.org/xz/xz-5.2.4.tar.gz.sig
Summary  : General purpose data compression library
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1 Public-Domain
Requires: xz-bin
Requires: xz-lib
Requires: xz-doc
Requires: xz-locales
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext-bin
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : openssl-dev
BuildRequires : pkg-config-dev
Patch1: default-threading.patch
Patch2: io-size.patch
Patch3: speedup.patch
Patch4: add-pgo.patch

%description
XZ Utils
========
0. Overview
1. Documentation
1.1. Overall documentation
1.2. Documentation for command-line tools
1.3. Documentation for liblzma
2. Version numbering
3. Reporting bugs
4. Translating the xz tool
5. Other implementations of the .xz format
6. Contact information

%package bin
Summary: bin components for the xz package.
Group: Binaries

%description bin
bin components for the xz package.


%package dev
Summary: dev components for the xz package.
Group: Development
Requires: xz-lib
Requires: xz-bin
Provides: xz-devel

%description dev
dev components for the xz package.


%package dev32
Summary: dev32 components for the xz package.
Group: Default
Requires: xz-lib32
Requires: xz-bin
Requires: xz-dev

%description dev32
dev32 components for the xz package.


%package doc
Summary: doc components for the xz package.
Group: Documentation

%description doc
doc components for the xz package.


%package lib
Summary: lib components for the xz package.
Group: Libraries

%description lib
lib components for the xz package.


%package lib32
Summary: lib32 components for the xz package.
Group: Default

%description lib32
lib32 components for the xz package.


%package locales
Summary: locales components for the xz package.
Group: Default

%description locales
locales components for the xz package.


%prep
%setup -q -n xz-5.2.4
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p2
pushd ..
cp -a xz-5.2.4 build32
popd
pushd ..
cp -a xz-5.2.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525035143
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%reconfigure --disable-static --enable-assume-ram=1024
make  %{?_smp_mflags} pgo-build
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%reconfigure --disable-static --enable-assume-ram=1024  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags} pgo-build
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%reconfigure --disable-static --enable-assume-ram=1024   --libdir=/usr/lib64/haswell --bindir=/usr/bin/haswell
make  %{?_smp_mflags} pgo-build
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1525035143
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd ../buildavx2/
%make_install
popd
%make_install
%find_lang xz

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/haswell/lzcat
%exclude /usr/bin/haswell/lzcmp
%exclude /usr/bin/haswell/lzdiff
%exclude /usr/bin/haswell/lzegrep
%exclude /usr/bin/haswell/lzfgrep
%exclude /usr/bin/haswell/lzgrep
%exclude /usr/bin/haswell/lzless
%exclude /usr/bin/haswell/lzma
%exclude /usr/bin/haswell/lzmadec
%exclude /usr/bin/haswell/lzmainfo
%exclude /usr/bin/haswell/lzmore
%exclude /usr/bin/haswell/unlzma
%exclude /usr/bin/haswell/unxz
%exclude /usr/bin/haswell/xz
%exclude /usr/bin/haswell/xzcat
%exclude /usr/bin/haswell/xzcmp
%exclude /usr/bin/haswell/xzdec
%exclude /usr/bin/haswell/xzdiff
%exclude /usr/bin/haswell/xzegrep
%exclude /usr/bin/haswell/xzfgrep
%exclude /usr/bin/haswell/xzgrep
%exclude /usr/bin/haswell/xzless
%exclude /usr/bin/haswell/xzmore
/usr/bin/lzcat
/usr/bin/lzcmp
/usr/bin/lzdiff
/usr/bin/lzegrep
/usr/bin/lzfgrep
/usr/bin/lzgrep
/usr/bin/lzless
/usr/bin/lzma
/usr/bin/lzmadec
/usr/bin/lzmainfo
/usr/bin/lzmore
/usr/bin/unlzma
/usr/bin/unxz
/usr/bin/xz
/usr/bin/xzcat
/usr/bin/xzcmp
/usr/bin/xzdec
/usr/bin/xzdiff
/usr/bin/xzegrep
/usr/bin/xzfgrep
/usr/bin/xzgrep
/usr/bin/xzless
/usr/bin/xzmore

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/lzma/base.h
/usr/include/lzma/bcj.h
/usr/include/lzma/block.h
/usr/include/lzma/check.h
/usr/include/lzma/container.h
/usr/include/lzma/delta.h
/usr/include/lzma/filter.h
/usr/include/lzma/hardware.h
/usr/include/lzma/index.h
/usr/include/lzma/index_hash.h
/usr/include/lzma/lzma12.h
/usr/include/lzma/stream_flags.h
/usr/include/lzma/version.h
/usr/include/lzma/vli.h
/usr/lib64/haswell/liblzma.so
/usr/lib64/liblzma.so
/usr/lib64/pkgconfig/liblzma.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/liblzma.so
/usr/lib32/pkgconfig/32liblzma.pc
/usr/lib32/pkgconfig/liblzma.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/xz/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/liblzma.so.5
/usr/lib64/haswell/liblzma.so.5.2.4
/usr/lib64/liblzma.so.5
/usr/lib64/liblzma.so.5.2.4

%files lib32
%defattr(-,root,root,-)
/usr/lib32/liblzma.so.5
/usr/lib32/liblzma.so.5.2.4

%files locales -f xz.lang
%defattr(-,root,root,-)

